kind: pipeline
type: docker

steps:
  - name: scan_fs
    image: registry.nextpertise.tools/nextpertise-proxy/aquasec/trivy:0.14.0
    commands:
      - trivy --light fs --quiet --exit-code 1 .
  - name: verify
    image: registry.nextpertise.tools/nextpertise/python-poetry:3.8
    commands:
      - poetry install
      - poetry run pytest
      - poetry run pylint src || exit 0 # Ignore pylint failures as they are not as important as tests
image_pull_secrets:
  - platform_harbor_pull_secrets
